### PR TITLE
Add support for nitrokey 3 distinction between the secrets app firmware and the device firmware versions

### LINKED ISSUE #38: Make Info Output more verbose for nk3
See also issue #36 
Change this:
```

HOTP code verification application, version 1.6
Connected device status:
	Card serial: 0x7BE66C6C
	Firmware: v4.13
	Card counters: Admin 6, User 6
Operation success
```
To
```
HOTP code verification application, version 1.6
Connected device status:
	Card serial: 0x7BE66C6C
        Firmware Nitrokey 3: v1.7.1
	Firmware Secrets app: v4.13
	Secret app pin counters : Admin 6, User 6
Operation success
```

### PR DESCRIPTION
**Pull request by sosthene-nitrokey**
Fix #38

### CODE REVIEW

**Comment by tlaurion** [comment]
@sosthene-nitrokey just want to make sure we are at the same page:

> <nk3
> ```
> HOTP code verification application, version 1.7
> Connected device status:
> Card serial: 0x7BE66C6C
>          Firmware Nitrokey 2: v1.7.1
> OpenPGP smartcard PIN counters : Admin: 3, User: 3
> Operation success
> ```
> 
> nk3:
> ```
> HOTP code verification application, version 1.7
> Connected device status:
> Card serial: 0x7BE66C6C
>          Firmware Nitrokey 3: v1.7.1
>          Firmware Secrets app: v4.13
> Secret app PIN counter : 6
> OpenPGP smartcard PIN counters : Admin: 3, User: 3
> Operation success
> ```

_Originally posted by @tlaurion in https://github.com/Nitrokey/nitrokey-hotp-verification/issues/38#issuecomment-2487450702_

**Comment by nestire** [comment]
Test with nk pr + nk stroage
```
ls -lh hotp_verification
-rwxr-xr-x 1 user user 59K Nov 27 11:20 hotp_verification
sha256sum hotp_verification
4a6db3c562d75bc637e23394080f3821c47774175780d8f72e45430fb9897181  hotp_verification
[user@work nitrokey-hotp-verification (more-info)]$ lsusb
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 013: ID 20a0:4108 Clay Logic Nitrokey Pro
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
[user@work nitrokey-hotp-verification (more-info)]$ ./hotp_verification info
HOTP code verification application, version 1.6

Connected device status:
	Card serial: 0xFFFFFFFF
	Firmware Nitrokey 3: v3.14980.0
	Firmware Secrets App: v255.0
	Card counters: Admin 3, User 3
Operation success
[user@work nitrokey-hotp-verification (more-info)]$ lsusb
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 014: ID 20a0:4109 Clay Logic Nitrokey Storage
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
[user@work nitrokey-hotp-verification (more-info)]$ ./hotp_verification info
HOTP code verification application, version 1.6

Connected device status:
	Card serial: 0xFFFFFFFF
	Firmware Nitrokey 3: v0.0.0
	Firmware Secrets App: v255.0
	Card counters: Admin 3, User 3
Operation success
[user@work nitrokey-hotp-verification (more-info)]$ 

```

**Comment by tlaurion** [comment]
> I repeat
> 
> You proposed :
> > See also issue #36 
> > Change this:
> > ```
> > 
> > HOTP code verification application, version 1.6
> > Connected device status:
> > 	Card serial: 0x7BE66C6C
> > 	Firmware: v4.13
> > 	Card counters: Admin 6, User 6
> > Operation success
> > ```
> > To
> > ```
> > HOTP code verification application, version 1.6
> > Connected device status:
> > 	Card serial: 0x7BE66C6C
> >         Firmware Nitrokey 3: v1.7.1
> > 	Firmware Secrets app: v4.13
> > 	Secret app pin counters : Admin 6, User 6
> > Operation success
> > ```
> 
> I proposed and restated:
> 
> **Even more sensical**: no secret app even named  anywhere because there is none on non nk3(regression), so no version of non existing secret app, no secret app pin, just real information :
> ```
> HOTP code verification application, version 1.7
> Connected device status:
> Card serial: 0x7BE66C6C
>          Firmware Nitrokey 2: v1.7.1
> OpenPGP smartcard PIN counters : Admin: 3, User: 3
> Operation success
> ```
> 
> For nk3:
> ```
> HOTP code verification application, version 1.7
> Connected device status:
> Card serial: 0x7BE66C6C
>          Firmware Nitrokey 3: v1.7.1
>          Firmware Secrets app: v4.13
> Secret app PIN counter : 6
> OpenPGP smartcard PIN counters : Admin: 3, User: 3
> Operation success
> ```
> 
> _Originally posted by @tlaurion in https://github.com/Nitrokey/nitrokey-hotp-verification/issues/38#issuecomment-2487450702_

**Comment by sosthene-nitrokey** [comment]
Updated to give the following with an NK3:

```
$ hotp_verification info
HOTP code verification application, version 1.6
...
Connected device status:
	Card serial: 0xADF72B1E
	Firmware Nitrokey 3: v1.8.0
	Firmware Secrets App: v4.13
	Secrets app PIN counter: 8
	GPG Card counters: Admin 3, User 3
Operation success
```

No change in a

**Review by daringer — APPROVED** [review]

**Pull request merged**
