### PR TITLE
Fix downstream issues with dynamic branding by merging LK/NK

### PR DESCRIPTION
**Pull request by MrChromebox**
Heads expects a single executable named 'hotp_verification' and
a single script named 'hotp_initialize' which takes the key branding
as its final argument.

Tested on Librem 13v2 via Heads

Signed-off-by: Matt DeVillier <matt.devillier@puri.sm>

### CODE REVIEW

**Comment by szszszsz** [comment]
Connected #11 , potentially duplicated.
FYI @alex-nitrokey

**Comment by szszszsz** [comment]
Hi @MrChromebox!
As far as I see your changes are a subset of #11. Could you confirm briefly? If so, I will close this one and merge #11.

**Comment by MrChromebox** [comment]
@szszszsz looks like it, let me test #11 later today and I will confirm and close accordingly

**Comment by MrChromebox** [comment]
#11 LGTM, closing this

**Pull request closed without merging**
